### ISSUE TITLE
covariates for each taxa

### ISSUE THREAD

**Issue by nussaibahrs** [josteist/Compadre#1]
Hi! Fantastic package, really much looking forward to using it. I had a question:

From your example, I can see you can have covariates for each time slices but I'm wondering if it's also possible to add covariates for each taxa, e.g.

| taxa    | var|        
| ---- |------|
| aa      | 1 |
| bb      | 2      |  
| cc | 2      |

**Comment by josteist** [comment]
Hei Nussaibah.
Thanks for you email, and interest. I'm sorry but for now covariate among
taxa is not incorporated in the package for now. This is of course
something that would be of interest to develop, but my time in the near
future will not be enough for such an extension.

Best
Jostein

**Comment by nussaibahrs** [comment]
Thanks for the answer! Much appreciate it. I look forward to further developments (on the long term).
