### ISSUE TITLE
Resetting plot parameters

### ISSUE THREAD

**Issue by nussaibahrs** [josteist/Compadre#2]
https://github.com/josteist/Compadre/blob/f4f64f0b989c68f30e650f691345df41afa0bfed/R/plotRates.R#L39

I would recommend to put this on line after line 19 or anywhere after `if(drawplot)`, else the plot parameters don't reset if `drawplot=FALSE`

**Comment by josteist** [comment]
Thanks for this - it was on my list and you pushed me to do it.
